ALTER TABLE `import_kota`
CHANGE COLUMN `CAR` `CAR_TARGET`  varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `KREDIT_TARGET`,
CHANGE COLUMN `ROA` `ROA_TARGET`  varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `CAR_TARGET`,
CHANGE COLUMN `ROE` `ROE_TARGET`  varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `ROA_TARGET`,
CHANGE COLUMN `BOPO` `BOPO_TARGET`  varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `ROE_TARGET`,
CHANGE COLUMN `CR` `CR_TARGET`  varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `BOPO_TARGET`,
CHANGE COLUMN `LDR` `LDR_TARGET`  varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `CR_TARGET`,
CHANGE COLUMN `KAP` `KAP_TARGET`  varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `LDR_TARGET`,
CHANGE COLUMN `NPL_GROSS` `NPL_GROSS_TARGET`  varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `KAP_TARGET`,
CHANGE COLUMN `NPL_NET` `NPL_NET_TARGET`  varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `NPL_GROSS_TARGET`,
CHANGE COLUMN `NIM` `NIM_TARGET`  varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `NPL_NET_TARGET`,
ADD COLUMN `CAR_REALISASI`  varchar(255) NULL AFTER `CAR_TARGET`,
ADD COLUMN `ROA_REALISASI`  varchar(255) NULL AFTER `ROA_TARGET`,
ADD COLUMN `ROE_REALISASI`  varchar(255) NULL AFTER `ROE_TARGET`,
ADD COLUMN `BOPO_REALISASI`  varchar(255) NULL AFTER `BOPO_TARGET`,
ADD COLUMN `CR_REALISASI`  varchar(255) NULL AFTER `CR_TARGET`,
ADD COLUMN `LDR_REALISASI`  varchar(255) NULL AFTER `LDR_TARGET`,
ADD COLUMN `KAP_REALISASI`  varchar(255) NULL AFTER `KAP_TARGET`,
ADD COLUMN `NPL_GROSS_REALISASI`  varchar(255) NULL AFTER `NPL_GROSS_TARGET`,
ADD COLUMN `NPL_NET_REALISASI`  varchar(255) NULL AFTER `NPL_NET_TARGET`,
ADD COLUMN `NIM_REALISASI`  varchar(255) NULL AFTER `NIM_TARGET`;

ALTER TABLE `import_kota`
MODIFY COLUMN `TAB_SURYA`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT 'TABUNGAN SURYA (UMUM)             ' AFTER `NIM_REALISASI`,
MODIFY COLUMN `ATM_KHUSUS`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT 'ATM TABUNGAN SURYA KHUSUS         ' AFTER `TAB_SURYA`,
MODIFY COLUMN `ATM_SURYA`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT 'ATM TABUNGAN SURYA UMUM           ' AFTER `ATM_KHUSUS`,
MODIFY COLUMN `TAB_PENSIUN`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT 'TABUNGAN PENSIUN' AFTER `ATM_SURYA`,
MODIFY COLUMN `TAS`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT 'TABUNGAN TAS CERIA                ' AFTER `TAB_PENSIUN`,
MODIFY COLUMN `TAB_KU`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT 'TABUNGANKU                        ' AFTER `TAS`,
MODIFY COLUMN `TAB_UMROH`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT 'TABUNGAN UMROH                    ' AFTER `TAB_KU`,
MODIFY COLUMN `THT_UMUM`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT 'TABUNGAN THT UMUM                 ' AFTER `TAB_UMROH`,
MODIFY COLUMN `TAB_SIMPEL`  varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL COMMENT 'TABUNGAN SIMPANAN PELAJAR (SIMPEL)' AFTER `THT_UMUM`;

