ALTER TABLE `kota`
ADD COLUMN `DELETED`  int NULL AFTER `STATUS`;

ALTER TABLE `jabatan_dir`
ADD COLUMN `KETERANGAN`  varchar(255) NULL AFTER `ID_DIREKSI`;

ALTER TABLE `linkage`
ADD COLUMN `DELETED`  int NULL AFTER `STATUS`;

ALTER TABLE `linkage`
MODIFY COLUMN `DELETED`  int(11) NOT NULL DEFAULT 0 AFTER `STATUS`;

ALTER TABLE `wilayah`
ADD COLUMN `DELETED`  int NULL DEFAULT 0 AFTER `STATUS`;

