ALTER TABLE `import_wilayah`
MODIFY COLUMN `ID_IMPORT`  int(11) NOT NULL AUTO_INCREMENT FIRST ;

ALTER TABLE `import_cabang`
MODIFY COLUMN `ID_IMPORT`  int(11) NOT NULL AUTO_INCREMENT FIRST ;

ALTER TABLE `import_kota`
MODIFY COLUMN `ID_IMPORT`  int(11) NOT NULL AUTO_INCREMENT FIRST ;

ALTER TABLE `import_kas`
MODIFY COLUMN `ID_IMPORT`  int(11) NOT NULL AUTO_INCREMENT FIRST ;

CREATE TABLE `d_linkage_kota` (
`ID_D_LINKAGE_KOTA`  int NOT NULL AUTO_INCREMENT ,
`ID_LINKAGE`  int NULL ,
`ID_KOTA`  int NULL ,
`TGL_PENCAIRAN`  date NULL ,
`TGL_JATUH_TEMPO`  date NULL ,
`SUKU_BUNGA`  double NULL ,
`PLATFOND`  varchar(255) NULL ,
`BAKI_DEBET`  varchar(255) NULL ,
`TIMESTAMP`  datetime NULL DEFAULT NULL,
PRIMARY KEY (`ID_D_LINKAGE_KOTA`)
)
;

ALTER TABLE `d_linkage_kota` ADD FOREIGN KEY (`ID_LINKAGE`, `ID_KOTA`) REFERENCES `linkage_kota` (`ID_LINKAGE`, `ID_KOTA`) ON DELETE CASCADE ON UPDATE CASCADE;

